# Generated by Django 6.0.2 on 2026-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='is_terminal',
            field=models.BooleanField(default=False),
        ),
    ]
